/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doandbms;
import com.mysql.jdbc.CallableStatement;
import java.util.Calendar;
import java.util.Date;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Son Thuol
 */
public class AddCa extends javax.swing.JFrame {

    /**
     * Creates new form AddCa
     */
    MySQLConnection connection = new MySQLConnection();
    DefaultTableModel tableModel;
    public AddCa() {
        initComponents();
        tableModel = (DefaultTableModel)DS_CaLam.getModel();
        ShowTC_CaLam();
        showTC_TTNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TC_MaNV = new javax.swing.JFormattedTextField();
        TC_BoxBuoi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        DS_CaLam = new javax.swing.JTable();
        TC_Ngay = new javax.swing.JComboBox<>();
        TC_Thang = new javax.swing.JComboBox<>();
        TC_Nam = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TC_Add = new javax.swing.JButton();
        TC_Box_CV = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TC_ghichu = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DS_nhanvien = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("THÊM CA LÀM");

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Buổi:");

        jLabel3.setBackground(new java.awt.Color(102, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã NV: ");

        jLabel4.setBackground(new java.awt.Color(102, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ngày làm:");

        TC_MaNV.setBackground(new java.awt.Color(255, 255, 255));
        TC_MaNV.setForeground(new java.awt.Color(0, 0, 0));
        TC_MaNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        TC_BoxBuoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng", "Chiều", "Tối" }));
        TC_BoxBuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_BoxBuoiActionPerformed(evt);
            }
        });

        DS_CaLam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Chức Vụ", "Mã Nhân Viên", "Họ Và Tên", "Ngày làm", "Buổi"
            }
        ));
        jScrollPane1.setViewportView(DS_CaLam);
        if (DS_CaLam.getColumnModel().getColumnCount() > 0) {
            DS_CaLam.getColumnModel().getColumn(3).setResizable(false);
            DS_CaLam.getColumnModel().getColumn(3).setHeaderValue("Ngày làm");
            DS_CaLam.getColumnModel().getColumn(4).setResizable(false);
            DS_CaLam.getColumnModel().getColumn(4).setHeaderValue("Buổi");
        }

        TC_Ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        TC_Thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        TC_Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ngày");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tháng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Năm");

        TC_Add.setBackground(new java.awt.Color(204, 204, 255));
        TC_Add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TC_Add.setForeground(new java.awt.Color(0, 0, 0));
        TC_Add.setText("Thêm Ca");
        TC_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_AddActionPerformed(evt);
            }
        });

        TC_Box_CV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TC_Box_CV.setForeground(new java.awt.Color(51, 51, 51));
        TC_Box_CV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thu Ngân", "Pha Chế", "Phục Vụ", "Lao Công" }));
        TC_Box_CV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TC_Box_CVMouseClicked(evt);
            }
        });
        TC_Box_CV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_Box_CVActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Lọc Theo Chức Vụ:");

        TC_ghichu.setBackground(new java.awt.Color(255, 255, 255));
        TC_ghichu.setColumns(20);
        TC_ghichu.setForeground(new java.awt.Color(0, 0, 0));
        TC_ghichu.setRows(5);
        jScrollPane2.setViewportView(TC_ghichu);

        jLabel10.setBackground(new java.awt.Color(102, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ghi chú");

        jLabel11.setBackground(new java.awt.Color(102, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("DANH SÁCH CA LÀM");

        DS_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Chức Vụ", "Mã Nhân Viên", "Họ Và Tên"
            }
        ));
        DS_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DS_nhanvienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(DS_nhanvien);

        jLabel12.setBackground(new java.awt.Color(102, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("DANH SÁCH NHÂN VIÊN");

        Exit.setText("Thoát");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TC_Ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TC_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TC_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TC_BoxBuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TC_MaNV)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel6)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(TC_Add)))
                        .addGap(24, 24, 24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TC_Box_CV, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Exit)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TC_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TC_Ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TC_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TC_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TC_BoxBuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TC_Add)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addComponent(TC_Box_CV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TC_BoxBuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_BoxBuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TC_BoxBuoiActionPerformed
    private String chuyendoiBuoi(String Buoi){
        String buoi = "";
        switch (Buoi){
            case "Sáng": {
                buoi = "S";
                break;
            }
            case "Chiều":{
                buoi = "C";
                break;
            }
            case "Tối":{
                buoi = "T";
                break;
            }
        }
        return buoi;
    }
    private boolean laNamNhuan(int Nam){
        if((Nam % 4 == 0 && Nam % 100 != 0) || Nam % 400 == 0)
            return true;
        else return false;
    }
    
    int tinhSoNgay(int thang, int nam){
        int  songay = 0;
        switch(thang){
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                songay = 31;
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                songay = 30;
                break;
            case 2:{
                if(laNamNhuan(nam)) songay = 29;
                else songay = 28;
                break;
            }
        }
        return songay;
    }
    //kiem tra ngya hop le
    private boolean laNgayHopLe(int nDay, int nMonth, int nYear){
	// Kiểm tra năm
	if (nYear < 0){
            return false; // Ngày không còn hợp lệ nữa!
	}
	// Kiểm tra tháng
	if (nMonth < 1 || nMonth > 12){
            return false; // Ngày không còn hợp lệ nữa!
	}
	// Kiểm tra ngày
        if (nDay < 1 || nDay > tinhSoNgay(nMonth, nYear)){
            return false; // Ngày không còn hợp lệ nữa!
	}
	return true; // Trả về trạng thái cuối cùng...
    }
    
    //reset 
    private void reset(){
        TC_MaNV.setText("");
        TC_Ngay.setSelectedIndex(0);
        TC_Thang.setSelectedIndex(0);
        TC_Nam.setSelectedIndex(0);
        TC_BoxBuoi.setSelectedItem(0);
        TC_ghichu.setText("");
    } 
        
    private boolean SauNgayHienTai(int ngay, int thang, int nam){
       Calendar c = Calendar.getInstance(); 
  
        // set Month 
        // MONTH starts with 0 i.e. ( 0 - Jan) 
        c.set(Calendar.MONTH, (thang-1)); 
  
        // set Date 
        c.set(Calendar.DATE, ngay); 
  
        // set Year 
        c.set(Calendar.YEAR, nam); 
  
        // creating a date object with specified time. 
        Date dateOne = c.getTime(); 
  
        // creating a date of object 
        // storing the current date 
        Date currentDate = new Date(); 
  
        //System.out.print("Is currentDate after date one : "); 
  
        // if currentDate is after dateOne 
        //System.out.println(currentDate.after(dateOne));
        return currentDate.after(dateOne);
    }
    private void TC_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_AddActionPerformed
        Connection conn = connection.ConnectMySQL();
        Statement Stmt = null;
        //lay du lieu tu from khi chung ta nhap du lieu
        String manv = String.valueOf(TC_MaNV.getText()).trim();
        String ngay = String.valueOf(TC_Ngay.getSelectedItem().toString().trim());
        String thang = String.valueOf(TC_Thang.getSelectedItem().toString().trim());
        String nam = String.valueOf(TC_Nam.getSelectedItem().toString().trim());
        String BUOI = String.valueOf(TC_BoxBuoi.getSelectedItem().toString().trim());
        //chuyen doi buoi thanh cac chu cai in hoa
        String buoi = chuyendoiBuoi(BUOI);
        String ghichu = TC_ghichu.getText();
        //noi chuoi thanh dang yyyy-mm-dd
        String NgayThang = nam+"-"+thang+"-"+ngay;
        //kiem tra sau ngay hien
        //Tức là thêm ca là ngày thêm ca phải lớn hơn ngay hiện tại
        //sau ngay hien tai  = true
        //truoc ngay hien tai = false
        boolean chekcdate = SauNgayHienTai(Integer.parseInt(ngay) , Integer.parseInt(thang), Integer.parseInt(nam));
        //kiem tra rong
        //kiem tra ngay hop le TH: 30/2
        //kiem tra sau ngay hien tai
        if(manv.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đầy đủ thông tin!!!", "Error", 1);
        }else if(laNgayHopLe(Integer.parseInt(ngay) , Integer.parseInt(thang), Integer.parseInt(nam)) == false){
                JOptionPane.showMessageDialog(rootPane, "Ngày đăng ký không hợp lệ! Yêu cầu chọn lại!", "Erro", 1);
        }else if(chekcdate == true){
            JOptionPane.showMessageDialog(rootPane, "Ngày đăng ký không hợp lệ! Yêu cầu chọn lại!", "Erro", 1);
        }else{
            boolean checktrung = true;
            try {
                CallableStatement cStmt_c = (CallableStatement) conn.prepareCall("{call kt_nv_trung(?,?,?)}");
                cStmt_c.setString(1, manv);
                cStmt_c.setString(2, NgayThang);
                cStmt_c.setString(3, buoi);
                ResultSet rs_checkid = cStmt_c.executeQuery();
                if(rs_checkid.next()){
                    JOptionPane.showMessageDialog(rootPane, "Nhân viên này đã trùng ca làm! Yêu cầu nhập mã lại", "Erro", 1);
                    checktrung = false;
                }else{
                    try{
                        CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call themca_nv(?,?,?,?)}");
                        cStmt.setString(1, manv);
                        cStmt.setString(2, NgayThang);
                        cStmt.setString(3, buoi);
                        cStmt.setString(4, ghichu);
                        ResultSet rs = cStmt.executeQuery();
                    }catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        ShowTC_CaLam();
        FormMain fm = new FormMain();
        fm.hienthiCaLam();
    }//GEN-LAST:event_TC_AddActionPerformed
    
    private String chucvu(String cv){
        String CV = "";
        switch (cv){
            case "Thu Ngân": {CV =  "TN"; break;}
            case "Pha Chế" : {CV =  "PC"; break;}
            case "Lao Công": {CV =  "LC"; break;}
            case "Phục Vụ" : {CV =  "PV"; break;}
        }
        return CV;
    }
    
    private void TC_Box_CVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_Box_CVActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        String chucvu = String.valueOf(TC_Box_CV.getSelectedItem()).toString().trim();
        Connection conn = connection.ConnectMySQL();
        Statement Stmt = null;
        ResultSet rs = null;
        try {
            String CV = chucvu(chucvu);
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call loc_chucvu(?)}");
            cStmt.setString(1, CV);
            rs = cStmt.executeQuery();
             while(rs.next()){
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                 //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
                tableModel= (DefaultTableModel)DS_nhanvien.getModel();
                tableModel.addRow(new String[]{macv, manv, tennv});
             }
        } catch (Exception e) {
            e.printStackTrace();
        }
        ShowTC_CaLam();
    }//GEN-LAST:event_TC_Box_CVActionPerformed

    private void DS_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DS_nhanvienMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel= (DefaultTableModel)DS_nhanvien.getModel();
        String manv = tableModel.getValueAt(DS_nhanvien.getSelectedRow(), 1).toString();
        TC_MaNV.setText(manv);
    }//GEN-LAST:event_DS_nhanvienMouseClicked

    private void TC_Box_CVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TC_Box_CVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TC_Box_CVMouseClicked

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed
    private void ShowTC_CaLam(){
    DefaultTableModel tableModel= (DefaultTableModel)DS_CaLam.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        Statement Stmt = null;
        ResultSet rs = null;
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call thongtin_calam()}");
            rs = cStmt.executeQuery();
            while(rs.next()){
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                 String dateNS = rs.getString("ngaylam");
                String NS[] = dateNS.split("-");
                String ngaylam = NS[2]+"/"+NS[1]+"/"+NS[0];
                String buoi = rs.getString("buoi");
                tableModel.addRow(new String[]{macv, manv, tennv, ngaylam, buoi});
            } 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void showTC_TTNV(){
        DefaultTableModel tableModel= (DefaultTableModel)DS_nhanvien.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        Statement Stmt = null;
        ResultSet rs = null;
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call hienthithongtinnhanvien()}");
            rs = cStmt.executeQuery();
            while(rs.next()){
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                tableModel.addRow(new String[]{macv, manv, tennv});
            } 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCa().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DS_CaLam;
    private javax.swing.JTable DS_nhanvien;
    private javax.swing.JButton Exit;
    private javax.swing.JButton TC_Add;
    private javax.swing.JComboBox<String> TC_BoxBuoi;
    private javax.swing.JComboBox<String> TC_Box_CV;
    private javax.swing.JFormattedTextField TC_MaNV;
    private javax.swing.JComboBox<String> TC_Nam;
    private javax.swing.JComboBox<String> TC_Ngay;
    private javax.swing.JComboBox<String> TC_Thang;
    private javax.swing.JTextArea TC_ghichu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
