/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doandbms;

import com.mysql.jdbc.CallableStatement;
import com.mysql.jdbc.Statement;
import java.math.RoundingMode;
import java.sql.ResultSet;
import java.sql.Connection;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Son Thuol
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormBANK
     */

    MySQLConnection connection = new MySQLConnection();
    DefaultTableModel tableModel;

    public FormMain() {
        initComponents();
        tableModel = (DefaultTableModel) jTableTTNV.getModel();
        HienThiTTNV();
        hienthiCaLam();
        LuongNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TTNV = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputNumPhone = new javax.swing.JFormattedTextField();
        inputName = new javax.swing.JFormattedTextField();
        inputAddress = new javax.swing.JFormattedTextField();
        inputFind = new javax.swing.JFormattedTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSortID = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        inputMa = new javax.swing.JFormattedTextField();
        BoxMaCV = new javax.swing.JComboBox<>();
        jButtonSortName = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTTNV = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        LocChucVu = new javax.swing.JComboBox<>();
        jButtonSortCv = new javax.swing.JButton();
        boxNgay = new javax.swing.JComboBox<>();
        boxThang = new javax.swing.JComboBox<>();
        boxNam = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jFormattedMaCaLam = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton_CL_Add = new javax.swing.JButton();
        jButton_CL_DS = new javax.swing.JButton();
        jButton_CL_Edit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_CL_Table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jFormattedTextField_L_Find = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox_L_Loai = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_LuongNV = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jComboBox_sapxepluong = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        Tu_N = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        Tu_T = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        Tu_Nam = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Den_N = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        Den_T = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        Den_Nam = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        TinhLuong_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ NHÂN VIÊN");

        TTNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TTNV.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TTNVAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("HỆ THỐNG QUẢN LÍ NHÂN VIÊN");

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Người thực hiện: Sơn Thươl");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(74, 74, 74)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(168, 168, 168))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        TTNV.addTab("TRANG CHỦ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        jLabel3.setBackground(new java.awt.Color(102, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Chọn Mã Chức Vụ");

        jLabel5.setBackground(new java.awt.Color(102, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nhập tên nhân viên:");

        jLabel6.setBackground(new java.awt.Color(102, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nhập ngày sinh:");

        jLabel7.setBackground(new java.awt.Color(102, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nhập số điện thoại:");

        jLabel8.setBackground(new java.awt.Color(102, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nhập địa chỉ:");

        inputNumPhone.setBackground(new java.awt.Color(255, 255, 255));
        inputNumPhone.setForeground(new java.awt.Color(0, 0, 0));
        inputNumPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputNumPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumPhoneActionPerformed(evt);
            }
        });
        inputNumPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNumPhoneKeyPressed(evt);
            }
        });

        inputName.setBackground(new java.awt.Color(255, 255, 255));
        inputName.setForeground(new java.awt.Color(0, 0, 0));
        inputName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });
        inputName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNameKeyPressed(evt);
            }
        });

        inputAddress.setBackground(new java.awt.Color(255, 255, 255));
        inputAddress.setForeground(new java.awt.Color(0, 0, 0));
        inputAddress.setToolTipText("");
        inputAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAddressActionPerformed(evt);
            }
        });

        inputFind.setBackground(new java.awt.Color(255, 255, 255));
        inputFind.setForeground(new java.awt.Color(0, 0, 0));
        inputFind.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFindActionPerformed(evt);
            }
        });
        inputFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputFindKeyReleased(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(102, 102, 102));
        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Sửa");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Thêm");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(102, 102, 102));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Xóa");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSortID.setBackground(new java.awt.Color(102, 102, 102));
        jButtonSortID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSortID.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSortID.setText("Sắp Xếp Theo Mã");
        jButtonSortID.setPreferredSize(new java.awt.Dimension(151, 22));
        jButtonSortID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortIDActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nhập mã nhân viên:");

        inputMa.setBackground(new java.awt.Color(255, 255, 255));
        inputMa.setForeground(new java.awt.Color(0, 0, 0));
        inputMa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputMa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMaActionPerformed(evt);
            }
        });
        inputMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputMaKeyPressed(evt);
            }
        });

        BoxMaCV.setBackground(new java.awt.Color(255, 255, 255));
        BoxMaCV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BoxMaCV.setForeground(new java.awt.Color(0, 0, 0));
        BoxMaCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thu Ngân", "Pha Chế", "Phục Vụ", "Lao Công" }));
        BoxMaCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMaCVActionPerformed(evt);
            }
        });

        jButtonSortName.setBackground(new java.awt.Color(102, 102, 102));
        jButtonSortName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSortName.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSortName.setText("Sắp Xếp Theo Tên");
        jButtonSortName.setMinimumSize(new java.awt.Dimension(151, 22));
        jButtonSortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortNameActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(102, 102, 102));
        jButtonReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonExit.setBackground(new java.awt.Color(102, 102, 102));
        jButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Thoát");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jTableTTNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại NV", "Mã NV", "Họ Và Tên", "Ngày Sinh", "Số Điện Thoại", "Địa Chỉ"
            }
        ));
        jTableTTNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTTNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTTNV);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Lọc Chức Vụ Nhân Viên:");

        LocChucVu.setBackground(new java.awt.Color(255, 255, 255));
        LocChucVu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LocChucVu.setForeground(new java.awt.Color(0, 0, 0));
        LocChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thu Ngân", "Lao Công", "Phục Vụ", "Pha Chế" }));
        LocChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocChucVuActionPerformed(evt);
            }
        });

        jButtonSortCv.setBackground(new java.awt.Color(102, 102, 102));
        jButtonSortCv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSortCv.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSortCv.setText("Sắp Xếp Theo ChucVu");
        jButtonSortCv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortCvActionPerformed(evt);
            }
        });

        boxNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        boxNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNgayActionPerformed(evt);
            }
        });

        boxThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        boxThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxThangActionPerformed(evt);
            }
        });

        boxNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));
        boxNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNamActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Ngày");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Tháng");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Năm");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Tìm Nhân Viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNumPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boxNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxThang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel17))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boxNam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputMa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LocChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonUpdate)
                                    .addComponent(jButtonAdd)
                                    .addComponent(jButtonDelete))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonExit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonReset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSortID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(inputFind)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSortCv, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(inputFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(BoxMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(19, 19, 19)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNumPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSortID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonUpdate)
                            .addComponent(jButtonExit)
                            .addComponent(jButtonSortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonSortCv))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(LocChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        TTNV.addTab("THÔNG TIN NHÂN VIÊN", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));

        jLabel11.setBackground(new java.awt.Color(102, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Mã Nhân Viên:");

        jFormattedMaCaLam.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedMaCaLam.setForeground(new java.awt.Color(0, 0, 0));
        jFormattedMaCaLam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("jLabel12");

        jButton_CL_Add.setBackground(new java.awt.Color(51, 255, 51));
        jButton_CL_Add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_CL_Add.setForeground(new java.awt.Color(0, 0, 0));
        jButton_CL_Add.setText("THÊM CA LÀM");
        jButton_CL_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CL_AddActionPerformed(evt);
            }
        });

        jButton_CL_DS.setBackground(new java.awt.Color(255, 255, 0));
        jButton_CL_DS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_CL_DS.setForeground(new java.awt.Color(0, 0, 0));
        jButton_CL_DS.setText("XÓA CA LÀM");
        jButton_CL_DS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CL_DSActionPerformed(evt);
            }
        });

        jButton_CL_Edit.setBackground(new java.awt.Color(255, 102, 204));
        jButton_CL_Edit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_CL_Edit.setForeground(new java.awt.Color(0, 0, 0));
        jButton_CL_Edit.setText("CHỈNH SỬA CA LÀM");
        jButton_CL_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CL_EditActionPerformed(evt);
            }
        });

        jTable_CL_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã CL", "Mã CV", "Mã NV", "Tên NV", "Ngày Làm", "Buổi", "Ghi Chú"
            }
        ));
        jTable_CL_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CL_TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_CL_Table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton_CL_Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_CL_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton_CL_DS, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CL_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CL_DS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CL_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        TTNV.addTab("CA LÀM", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jFormattedTextField_L_Find.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField_L_Find.setForeground(new java.awt.Color(0, 0, 0));
        jFormattedTextField_L_Find.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jFormattedTextField_L_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_L_FindActionPerformed(evt);
            }
        });
        jFormattedTextField_L_Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField_L_FindKeyReleased(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("XEM THEO LOẠI NV:");

        jComboBox_L_Loai.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_L_Loai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox_L_Loai.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_L_Loai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pha Chế", "Phục Vụ", "Thu Ngân", "Lao Công" }));
        jComboBox_L_Loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_L_LoaiActionPerformed(evt);
            }
        });

        Table_LuongNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên NV", "Chức Vụ", "Đơn Giá", "Số Ca", "Lương"
            }
        ));
        jScrollPane3.setViewportView(Table_LuongNV);

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("SẮP XẾP THEO: ");

        jComboBox_sapxepluong.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_sapxepluong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox_sapxepluong.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_sapxepluong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lương Tăng Dần", "Lương Giảm Dần" }));
        jComboBox_sapxepluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_sapxepluongActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("TÍNH LƯƠNG BẮT ĐẦU");

        Tu_N.setBackground(new java.awt.Color(255, 255, 255));
        Tu_N.setForeground(new java.awt.Color(0, 0, 0));
        Tu_N.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Tu_N.setPreferredSize(new java.awt.Dimension(60, 22));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Ngày:");

        Tu_T.setBackground(new java.awt.Color(255, 255, 255));
        Tu_T.setForeground(new java.awt.Color(0, 0, 0));
        Tu_T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        Tu_T.setPreferredSize(new java.awt.Dimension(60, 22));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Tháng:");

        Tu_Nam.setBackground(new java.awt.Color(255, 255, 255));
        Tu_Nam.setForeground(new java.awt.Color(0, 0, 0));
        Tu_Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022" }));
        Tu_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tu_NamActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Năm");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("TÌM NHÂN VIÊN:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Ngày:");

        Den_N.setBackground(new java.awt.Color(255, 255, 255));
        Den_N.setForeground(new java.awt.Color(0, 0, 0));
        Den_N.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Den_N.setPreferredSize(new java.awt.Dimension(60, 22));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Tháng:");

        Den_T.setBackground(new java.awt.Color(255, 255, 255));
        Den_T.setForeground(new java.awt.Color(0, 0, 0));
        Den_T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        Den_T.setPreferredSize(new java.awt.Dimension(60, 22));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Năm");

        Den_Nam.setBackground(new java.awt.Color(255, 255, 255));
        Den_Nam.setForeground(new java.awt.Color(0, 0, 0));
        Den_Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022" }));
        Den_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Den_NamActionPerformed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("TỪ:");

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("ĐẾN");

        TinhLuong_.setBackground(new java.awt.Color(255, 255, 255));
        TinhLuong_.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TinhLuong_.setForeground(new java.awt.Color(0, 0, 0));
        TinhLuong_.setText("Tính Lương");
        TinhLuong_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinhLuong_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel29))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Den_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Den_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel28)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Den_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Tu_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Tu_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Tu_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TinhLuong_)
                                            .addComponent(jLabel14))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_L_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_sapxepluong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextField_L_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_L_Find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox_L_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox_sapxepluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tu_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(Tu_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(Tu_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Den_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(Den_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(Den_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(TinhLuong_)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        TTNV.addTab("LƯƠNG", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TTNV, javax.swing.GroupLayout.PREFERRED_SIZE, 815, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TTNV)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TTNVAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TTNVAncestorAdded
        // TODO add your handling code here:
        HienThiTTNV();
    }//GEN-LAST:event_TTNVAncestorAdded

    private void TinhLuong_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinhLuong_ActionPerformed
        // TODO add your handling code here:
        //lay du lieu tu ngay nao do
        String Tu_ngay = String.valueOf(Tu_N.getSelectedItem().toString().trim());
        String Tu_thang = String.valueOf(Tu_T.getSelectedItem().toString().trim());
        String Tu_nam = String.valueOf(Tu_Nam.getSelectedItem().toString().trim());
        //den ngay nao do
        String Den_ngay = String.valueOf(Den_N.getSelectedItem().toString().trim());
        String Den_thang = String.valueOf(Den_T.getSelectedItem().toString().trim());
        String Den_nam = String.valueOf(Den_Nam.getSelectedItem().toString().trim());
        //dinh dang ngay;
        String NgayThang_TU = Tu_nam + "-" + Tu_thang + "-" + Tu_ngay;
        String NgayThang_DEN = Den_nam + "-" + Den_thang + "-" + Den_ngay;

        int kiemtra_tungay_nhohon_denngay = NgayThang_TU.compareTo(NgayThang_DEN);

        boolean chekcdateTu = SauNgayHienTai(Integer.parseInt(Tu_ngay), Integer.parseInt(Tu_thang), Integer.parseInt(Tu_nam));
        boolean chekcdateDen = SauNgayHienTai(Integer.parseInt(Den_ngay), Integer.parseInt(Den_thang), Integer.parseInt(Den_nam));
        boolean hopleDateTu = laNgayHopLe(Integer.parseInt(Tu_ngay), Integer.parseInt(Tu_thang), Integer.parseInt(Tu_nam));
        boolean hopleDateDen = laNgayHopLe(Integer.parseInt(Den_ngay), Integer.parseInt(Den_thang), Integer.parseInt(Den_nam));

        if (hopleDateTu == false) {
            JOptionPane.showMessageDialog(rootPane, "Ngày Tính lương không hợp lê", "Erro", 1);
        } else if (hopleDateDen == false) {
            JOptionPane.showMessageDialog(rootPane, "Ngày Tính lương không hợp lê", "Erro", 1);
        } else if (kiemtra_tungay_nhohon_denngay > 0) {
            JOptionPane.showMessageDialog(rootPane, "Ngày Tính lương không hợp lê (Ngày bắt đầu tính phải lớn hơn đến ngày tính)", "Erro", 1);
        } else if (chekcdateTu == false) {
            JOptionPane.showMessageDialog(rootPane, "Ngày Tính lương không hợp lê (Các Ngày Phải Sau Ngày Hiện Tại)", "Erro", 1);
        } else if (chekcdateDen == false) {
            JOptionPane.showMessageDialog(rootPane, "Ngày Tính lương không hợp lê (Các Ngày Phải Sau Ngày Hiện Tại)", "Erro", 1);
        }else{
            try {
            Connection conn = connection.ConnectMySQL();
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call tinhluongnhanvien(?,?)}");
            cStmt.setString(1, NgayThang_TU);
            cStmt.setString(2,NgayThang_DEN);
            ResultSet rs = cStmt.executeQuery();
            tableModel = (DefaultTableModel) Table_LuongNV.getModel();
            tableModel.setRowCount(0);
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                double luongfomat  = Double.parseDouble(luong);
                double dongiafm = Double.parseDouble(dongia);
                Locale locale = new Locale("vi", "VN");
                NumberFormat format = NumberFormat.getCurrencyInstance(locale);
                format.setRoundingMode(RoundingMode.HALF_UP);
                tableModel.addRow(new String[]{manv, tennv, cv,format.format(dongiafm), sc, format.format(luongfomat)});
            }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_TinhLuong_ActionPerformed

    private void Den_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Den_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Den_NamActionPerformed

    private void Tu_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tu_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tu_NamActionPerformed

    private void jComboBox_sapxepluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_sapxepluongActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) Table_LuongNV.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        String luachon = String.valueOf(jComboBox_sapxepluong.getSelectedItem()).toString().trim();
        try {
            CallableStatement cStmt = null;
            if(luachon.equals("Lương Tăng Dần")){
                cStmt = (CallableStatement) conn.prepareCall("{call sapxepluongtangdan()}");

            }else if(luachon.equals("Lương Giảm Dần")){
                cStmt = (CallableStatement) conn.prepareCall("{call sapxepluonggiamdan()}");
            }
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                double luongfomat  = Double.parseDouble(luong);
                double dongiafm = Double.parseDouble(dongia);
                Locale locale = new Locale("vi", "VN");
                NumberFormat format = NumberFormat.getCurrencyInstance(locale);
                format.setRoundingMode(RoundingMode.HALF_UP);
                tableModel.addRow(new String[]{manv, tennv, cv,format.format(dongiafm), sc, format.format(luongfomat)});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox_sapxepluongActionPerformed

    private void jComboBox_L_LoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_L_LoaiActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) Table_LuongNV.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        String chucvu = String.valueOf(jComboBox_L_Loai.getSelectedItem()).toString().trim();
        String CV = chucvu(chucvu);
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call LocNVtrongBangLuong(?)}");
            cStmt.setString(1, CV);
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                double luongfomat  = Double.parseDouble(luong);
                double dongiafm = Double.parseDouble(dongia);
                Locale locale = new Locale("vi", "VN");
                NumberFormat format = NumberFormat.getCurrencyInstance(locale);
                format.setRoundingMode(RoundingMode.HALF_UP);
                tableModel.addRow(new String[]{manv, tennv, cv,format.format(dongiafm), sc, format.format(luongfomat)});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox_L_LoaiActionPerformed

    private void jFormattedTextField_L_FindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_L_FindKeyReleased
        // TODO add your handling code here:
        Connection conn = (Connection) connection.ConnectMySQL();
        tableModel = (DefaultTableModel) Table_LuongNV.getModel();
        ResultSet rs = null;
        String input = null;
        try {
            input = String.valueOf(jFormattedTextField_L_Find.getText());
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call timNVtrongBangLuong(?)}");
            cStmt.setString(1, input);
            rs = cStmt.executeQuery();
            tableModel.setRowCount(0);
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                double luongfomat  = Double.parseDouble(luong);
                double dongiafm = Double.parseDouble(dongia);
                Locale locale = new Locale("vi", "VN");
                NumberFormat format = NumberFormat.getCurrencyInstance(locale);
                format.setRoundingMode(RoundingMode.HALF_UP);
                tableModel.addRow(new String[]{manv, tennv, cv,format.format(dongiafm), sc, format.format(luongfomat)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Không có thông tin nhân viên bạn cần tìm", "ERROR", 1);
        }
    }//GEN-LAST:event_jFormattedTextField_L_FindKeyReleased

    private void jFormattedTextField_L_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_L_FindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_L_FindActionPerformed

    private void jTable_CL_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CL_TableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_CL_TableMouseClicked

    private void jButton_CL_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CL_EditActionPerformed
        // TODO add your handling code here:
        Edit_CaLam editcalam = new Edit_CaLam();
        editcalam.show();
    }//GEN-LAST:event_jButton_CL_EditActionPerformed

    private void jButton_CL_DSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CL_DSActionPerformed
        // TODO add your handling code here:
        //thực hiện câu truy vấn
        DefaultTableModel tableModel = (DefaultTableModel) jTable_CL_Table.getModel();
        Connection conn = connection.ConnectMySQL();
        try {
            String macl = tableModel.getValueAt(jTable_CL_Table.getSelectedRow(), 0).toString();
            int a = JOptionPane.showConfirmDialog(rootPane, "Bạn Có Chắc xóa ca làm này chứ ?");
            if (a == JOptionPane.YES_OPTION) {
                CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call xoa_calam(?)}");
                cStmt.setString(1, macl);
                ResultSet rs = cStmt.executeQuery();
                reset();
                hienthiCaLam();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_CL_DSActionPerformed

    private void jButton_CL_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CL_AddActionPerformed
        // TODO add your handling code here:
        AddCa themca = new AddCa();
        themca.show();
    }//GEN-LAST:event_jButton_CL_AddActionPerformed

    private void boxNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNamActionPerformed

    private void boxThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxThangActionPerformed

    private void boxNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNgayActionPerformed

    private void jButtonSortCvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortCvActionPerformed
        // TODO add your handling code here:
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call chucvunv_sapxep()}");
            ResultSet rs = cStmt.executeQuery();
            tableModel.setRowCount(0);
            while (rs.next()) {
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                String dateNS = rs.getString("ngaysinh");
                String NS[] = dateNS.split("-");
                String ngaysinh = NS[2] + "/" + NS[1] + "/" + NS[0];
                String sodt = rs.getString("sodt");
                String diachi = rs.getString("diachi");
                //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
                tableModel = (DefaultTableModel) jTableTTNV.getModel();
                tableModel.addRow(new String[]{macv, manv, tennv, ngaysinh, sodt, diachi});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSortCvActionPerformed

    private void LocChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocChucVuActionPerformed
        // TODO add your handling code here:
        String chucvu = String.valueOf(LocChucVu.getSelectedItem()).toString().trim();
        Connection conn = connection.ConnectMySQL();
        try {
            String CV = chucvu(chucvu);
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call loc_chucvu(?)}");
            cStmt.setString(1, CV);
            ResultSet rs = cStmt.executeQuery();
            tableModel.setRowCount(0);
            while (rs.next()) {
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                String dateNS = rs.getString("ngaysinh");
                String NS[] = dateNS.split("-");
                String ngaysinh = NS[2] + "/" + NS[1] + "/" + NS[0];
                String sodt = rs.getString("sodt");
                String diachi = rs.getString("diachi");
                tableModel = (DefaultTableModel) jTableTTNV.getModel();
                tableModel.addRow(new String[]{macv, manv, tennv, ngaysinh, sodt, diachi});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_LocChucVuActionPerformed

    private void jTableTTNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTTNVMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTableTTNV.getModel();

        String manv = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 1).toString();
        String macv = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 0).toString();
        String tennv = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 2).toString();
        String ngaysinh = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 3).toString();
        String NS[] = ngaysinh.split("/");
        String sodt = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 4).toString();
        String diachi = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 5).toString();

        inputMa.setText(manv);
        BoxMaCV.setSelectedItem(macv);
        inputName.setText(tennv);
        boxNgay.setSelectedItem(NS[0]);
        boxThang.setSelectedItem(NS[1]);
        boxNam.setSelectedItem(NS[2]);
        inputNumPhone.setText(sodt);
        inputAddress.setText(diachi);
    }//GEN-LAST:event_jTableTTNVMouseClicked

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonSortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortNameActionPerformed
        // TODO add your handling code here:
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call tennv_sapxep()}");
            ResultSet rs = cStmt.executeQuery();
            tableModel.setRowCount(0);
            while (rs.next()) {
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                String dateNS = rs.getString("ngaysinh");
                String NS[] = dateNS.split("-");
                String ngaysinh = NS[2] + "/" + NS[1] + "/" + NS[0];
                String sodt = rs.getString("sodt");
                String diachi = rs.getString("diachi");
                //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
                tableModel = (DefaultTableModel) jTableTTNV.getModel();
                tableModel.addRow(new String[]{macv, manv, tennv, ngaysinh, sodt, diachi});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSortNameActionPerformed

    private void BoxMaCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxMaCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxMaCVActionPerformed

    private void inputMaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMaKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            inputMa.setEditable(false);
        } else {
            inputMa.setEditable(true);
        }
    }//GEN-LAST:event_inputMaKeyPressed

    private void inputMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMaActionPerformed

    private void jButtonSortIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortIDActionPerformed
        // TODO add your handling code here:
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call manv_sapxep()}");
            ResultSet rs = cStmt.executeQuery();
            tableModel.setRowCount(0);
            while (rs.next()) {
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                String dateNS = rs.getString("ngaysinh");
                String NS[] = dateNS.split("-");
                String ngaysinh = NS[2] + "/" + NS[1] + "/" + NS[0];
                String sodt = rs.getString("sodt");
                String diachi = rs.getString("diachi");
                tableModel = (DefaultTableModel) jTableTTNV.getModel();
                tableModel.addRow(new String[]{macv, manv, tennv, ngaysinh, sodt, diachi});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSortIDActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        Connection conn = (Connection) connection.ConnectMySQL();
        //lay du lieu tu bang
        String manv = String.valueOf(inputMa.getText()).trim();
        String macv = String.valueOf(BoxMaCV.getSelectedItem().toString().trim());
        String tennv = String.valueOf(inputName.getText()).trim();
        String ngay = String.valueOf(boxNgay.getSelectedItem().toString().trim());
        String thang = String.valueOf(boxThang.getSelectedItem().toString().trim());
        String nam = String.valueOf(boxNam.getSelectedItem().toString().trim());
        String sodt = String.valueOf(inputNumPhone.getText()).trim();
        String diachi = String.valueOf(inputAddress.getText()).trim();

        if (manv.equals("") || macv.equals("") || tennv.equals("") || ngay.equals("")
            || thang.equals("") || nam.equals("") || sodt.equals("") || diachi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bận cần  xóa nhân viên nào ?", "Erro", 1);
        } else {
            try {
                DefaultTableModel tableModel = (DefaultTableModel) jTableTTNV.getModel();
                String getmanv = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 1).toString();
                CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call xoa_nhanvien(?)}");
                cStmt.setString(1, getmanv);
                int a = JOptionPane.showConfirmDialog(rootPane, "Bạn Có Chắc xóa nhân viên này chứ ?");
                if (a == JOptionPane.YES_OPTION) {
                    ResultSet rs = cStmt.executeQuery();
                    reset();
                    HienThiTTNV();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        Connection conn = (Connection) connection.ConnectMySQL();
        HienThiTTNV();
        //lay du lieu tu bang
        String manv = String.valueOf(inputMa.getText()).trim();
        String CV = String.valueOf(BoxMaCV.getSelectedItem().toString().trim());
        String macv = chucvu(CV);
        String tennv = String.valueOf(inputName.getText()).trim();
        String ngay = String.valueOf(boxNgay.getSelectedItem().toString().trim());
        String thang = String.valueOf(boxThang.getSelectedItem().toString().trim());
        String nam = String.valueOf(boxNam.getSelectedItem().toString().trim());
        String sodt = String.valueOf(inputNumPhone.getText()).trim();
        String diachi = String.valueOf(inputAddress.getText()).trim();
        /*
        Kiểm tra xem các trường có trống hay không nếu có thì thông báo lỗi.
        */
        if (manv.equals("") || macv.equals("") || tennv.equals("") || ngay.equals("")
            || thang.equals("") || nam.equals("") || sodt.equals("") || diachi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đầy đủ thông tin", "Erro", 1);
        } else if (laNgayHopLe(Integer.parseInt(ngay), Integer.parseInt(thang), Integer.parseInt(nam)) == false) {
            JOptionPane.showMessageDialog(rootPane, "Ngày sinh không hợp lệ! Yêu cầu chọn ngày sinh lại!", "Erro", 1);
        } else {
            //Thêm thông tin vào database.
            try {
                CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call kiemtratontainhanvien(?)}");
                cStmt.setString(1, manv);
                ResultSet rs_checkid = cStmt.executeQuery();
                while (rs_checkid.next()) {
                    String ma = rs_checkid.getString("ma_nv");
                    if (ma.equals(manv)) {
                        JOptionPane.showMessageDialog(rootPane, "Mã nhân viên đã trùng! Yêu cầu nhập mã lại", "Error", 1);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call themthongtinnhanvien(?,?,?,?,?,?)}");
                cStmt.setString(1, manv);
                cStmt.setString(2, macv);
                cStmt.setString(3, tennv);
                cStmt.setString(4, nam + "-" + thang + "-" + ngay);
                cStmt.setString(5, sodt);
                cStmt.setString(6, diachi);
                ResultSet rs = cStmt.executeQuery();
                String ngaysinh = ngay + "/" + thang + "/" + nam;
                tableModel.addRow(new String[]{macv, manv, tennv, ngaysinh, sodt, diachi});
                reset();
            } catch (Exception e) {
                e.getStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    /* Chinh sua thong tin nhan vien*/
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        Connection conn = (Connection) connection.ConnectMySQL();
        //lay du lieu tu bang
        String manv = String.valueOf(inputMa.getText()).trim();
        String CV = String.valueOf(BoxMaCV.getSelectedItem().toString().trim());
        String macv = chucvu(CV);
        String tennv = String.valueOf(inputName.getText()).trim();
        String ngay = String.valueOf(boxNgay.getSelectedItem().toString().trim());
        String thang = String.valueOf(boxThang.getSelectedItem().toString().trim());
        String nam = String.valueOf(boxNam.getSelectedItem().toString().trim());
        String sodt = String.valueOf(inputNumPhone.getText()).trim();
        String diachi = String.valueOf(inputAddress.getText()).trim();
        /*
        Kiểm tra xem các trường có trống hay không nếu có thì thông báo lỗi.
        */
        if (manv.equals("") || macv.equals("") || tennv.equals("") || ngay.equals("")
            || thang.equals("") || nam.equals("") || sodt.equals("") || diachi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đầy đủ thông tin", "Erro", 1);
        } else {
            //Thêm thông tin vào database.
            try {
                CallableStatement cStmt = (CallableStatement) conn.prepareCall("call sua_thongtinnhanvien(?,?,?,?,?,?)");
                cStmt.setString(1, manv);
                cStmt.setString(2, macv);
                cStmt.setString(3, tennv);
                cStmt.setString(4, nam + "-" + thang + "-" + ngay);
                cStmt.setString(5, sodt);
                cStmt.setString(6, diachi);
                ResultSet rs = cStmt.executeQuery();
                HienThiTTNV();
                reset();
            } catch (Exception e) {
                e.getStackTrace();
            }
        }
        hienthiCaLam();
        LuongNhanVien();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void inputFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFindKeyReleased
        // TODO add your handling code here:
        Connection conn = (Connection) connection.ConnectMySQL();
        ResultSet rs = null;
        String input = null;
        try {
            input = String.valueOf(inputFind.getText());
            //luu cac ten nhavien vao mot danh sach
            if (input.equals("")) {
                HienThiTTNV();
            } else {
                CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call timthongtinnhanvien(?)}");
                cStmt.setString(1, input);
                rs = cStmt.executeQuery();
                tableModel.setRowCount(0);
                while (rs.next()) {
                    String manv = rs.getString("ma_nv");
                    String macv = rs.getString("ma_cv");
                    String tennv = rs.getString("ten_nv");
                    String dateNS = rs.getString("ngaysinh");
                    String NS[] = dateNS.split("-");
                    String ngaysinh = NS[2] + "/" + NS[1] + "/" + NS[0];
                    String sodt = rs.getString("sodt");
                    String diachi = rs.getString("diachi");
                    //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
                    tableModel = (DefaultTableModel) jTableTTNV.getModel();
                    tableModel.addRow(new String[]{macv, manv, tennv, ngaysinh, sodt, diachi});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Không có thông tin nhân viên bạn cần tìm", "ERROR", 1);
        }
    }//GEN-LAST:event_inputFindKeyReleased

    private void inputFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFindActionPerformed

    private void inputAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAddressActionPerformed

    private void inputNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNameKeyPressed

    }//GEN-LAST:event_inputNameKeyPressed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void inputNumPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNumPhoneKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            inputNumPhone.setEditable(false);
        } else {
            inputNumPhone.setEditable(true);
        }
    }//GEN-LAST:event_inputNumPhoneKeyPressed

    private void inputNumPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumPhoneActionPerformed

    private void HienThiTTNV() {
        DefaultTableModel tableModel = (DefaultTableModel) jTableTTNV.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = null;
            cStmt = (CallableStatement) conn.prepareCall("{call hienthithongtinnhanvien()}");
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                String dateNS = rs.getString("ngaysinh");
                String NS[] = dateNS.split("-");
                String ngaysinh = NS[2] + "/" + NS[1] + "/" + NS[0];
                String sodt = rs.getString("sodt");
                String diachi = rs.getString("diachi");
                //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
                tableModel.addRow(new String[]{macv, manv, tennv, ngaysinh, sodt, diachi});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean laNamNhuan(int Nam) {
        if ((Nam % 4 == 0 && Nam % 100 != 0) || Nam % 400 == 0) {
            return true;
        } else {
            return false;
        }
    }

    int tinhSoNgay(int thang, int nam) {
        int songay = 0;
        switch (thang) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                songay = 31;
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                songay = 30;
                break;
            case 2: {
                if (laNamNhuan(nam)) {
                    songay = 29;
                } else {
                    songay = 28;
                }
                break;
            }
        }
        return songay;
    }

    private boolean laNgayHopLe(int nDay, int nMonth, int nYear) {
        // Kiểm tra năm
        if (nYear < 0) {
            return false; // Ngày không còn hợp lệ nữa!
        }
        // Kiểm tra tháng
        if (nMonth < 1 || nMonth > 12) {
            return false; // Ngày không còn hợp lệ nữa!
        }
        // Kiểm tra ngày
        if (nDay < 1 || nDay > tinhSoNgay(nMonth, nYear)) {
            return false; // Ngày không còn hợp lệ nữa!
        }
        return true; // Trả về trạng thái cuối cùng...
    }

    //Reset lai du lieu
    private void reset() {
        inputMa.setText("");
        BoxMaCV.setSelectedIndex(0);
        inputName.setText("");
        boxNgay.setSelectedIndex(0);
        boxThang.setSelectedIndex(0);
        boxNam.setSelectedIndex(0);
        inputNumPhone.setText("");
        inputAddress.setText("");
    }

    private String chucvu(String cv) {
        String CV = "";
        switch (cv) {
            case "Thu Ngân": {
                CV = "TN";
                break;
            }
            case "Pha Chế": {
                CV = "PC";
                break;
            }
            case "Lao Công": {
                CV = "LC";
                break;
            }
            case "Phục Vụ": {
                CV = "PV";
                break;
            }
        }
        return CV;
    }
    
    public void hienthiCaLam() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable_CL_Table.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        Statement Stmt = null;
        ResultSet rs = null;
        try {
            Stmt = (Statement) conn.createStatement();
            String query = "select cl.ma_calam, nv.ma_cv, nv.ten_nv, cl.ma_nv, cl.ngaylam, cl.buoi, cl.ghichu "
                    + "from nhanvien nv, calam cl  where nv.ma_nv = cl.ma_nv order by cl.ngaylam";
            rs = Stmt.executeQuery(query);
            while (rs.next()) {
                String macl = rs.getString("ma_calam");
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                String dateNS = rs.getString("ngaylam");
                String NS[] = dateNS.split("-");
                String ngaylam = NS[2] + "/" + NS[1] + "/" + NS[0];
                String buoi = rs.getString("buoi");
                String ghichu = rs.getString("ghichu");
                //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
                tableModel.addRow(new String[]{macl, macv, manv, tennv, ngaylam, buoi, ghichu});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void LuongNhanVien() {
        DefaultTableModel tableModel = (DefaultTableModel) Table_LuongNV.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call hienthiluong()}");
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                double luongfomat  = Double.parseDouble(luong);
                double dongiafm = Double.parseDouble(dongia);
                Locale locale = new Locale("vi", "VN");
                NumberFormat format = NumberFormat.getCurrencyInstance(locale);
                format.setRoundingMode(RoundingMode.HALF_UP);
                tableModel.addRow(new String[]{manv, tennv, cv,format.format(dongiafm), sc, format.format(luongfomat)});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean SauNgayHienTai(int ngay, int thang, int nam) {
        Calendar c = Calendar.getInstance();

        // set Month 
        // MONTH starts with 0 i.e. ( 0 - Jan) 
        c.set(Calendar.MONTH, (thang - 1));

        // set Date 
        c.set(Calendar.DATE, ngay);

        // set Year 
        c.set(Calendar.YEAR, nam);

        // creating a date object with specified time. 
        Date dateOne = c.getTime();

        // creating a date of object 
        // storing the current date 
        Date currentDate = new Date();

        //System.out.print("Is currentDate after date one : "); 
        // if currentDate is after dateOne 
        //System.out.println(currentDate.after(dateOne));
        return currentDate.after(dateOne);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxMaCV;
    private javax.swing.JComboBox<String> Den_N;
    private javax.swing.JComboBox<String> Den_Nam;
    private javax.swing.JComboBox<String> Den_T;
    private javax.swing.JComboBox<String> LocChucVu;
    private javax.swing.JTabbedPane TTNV;
    private javax.swing.JTable Table_LuongNV;
    private javax.swing.JButton TinhLuong_;
    private javax.swing.JComboBox<String> Tu_N;
    private javax.swing.JComboBox<String> Tu_Nam;
    private javax.swing.JComboBox<String> Tu_T;
    private javax.swing.JComboBox<String> boxNam;
    private javax.swing.JComboBox<String> boxNgay;
    private javax.swing.JComboBox<String> boxThang;
    private javax.swing.JFormattedTextField inputAddress;
    private javax.swing.JFormattedTextField inputFind;
    private javax.swing.JFormattedTextField inputMa;
    private javax.swing.JFormattedTextField inputName;
    private javax.swing.JFormattedTextField inputNumPhone;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSortCv;
    private javax.swing.JButton jButtonSortID;
    private javax.swing.JButton jButtonSortName;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButton_CL_Add;
    private javax.swing.JButton jButton_CL_DS;
    private javax.swing.JButton jButton_CL_Edit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_L_Loai;
    private javax.swing.JComboBox<String> jComboBox_sapxepluong;
    private javax.swing.JFormattedTextField jFormattedMaCaLam;
    private javax.swing.JFormattedTextField jFormattedTextField_L_Find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableTTNV;
    private javax.swing.JTable jTable_CL_Table;
    // End of variables declaration//GEN-END:variables
}
